CargoXpress/Controllers/JobsFinderController.cs
using CargoXpress.Common;
using CargoXpress.Common.Paging;
using CargoXpress.Entities.Contract;
using CargoXpress.Entities.V1;
using CargoXpress.Infrastructure;
using CargoXpress.Pages;
using CargoXpress.Services.Contract;
using DataTables.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Device.Location;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static CargoXpress.Infrastructure.Enums;

namespace CargoXpress.Controllers
{
    public class JobsFinderController : BaseController
    {
        #region Fields
        
        private readonly AbstractJobBidsServices jobBidsServices;
        private readonly AbstractJobActivityServices jobActivityServices;
        private readonly AbstractJobServices jobServices;
        private readonly AbstractJobDriverCommentsServices jobDriverCommentsServices;
        private readonly AbstractJobCommentsServices jobCommentsServices;
        private readonly AbstractJobDocumentsServices jobDocumentsServices;
        private readonly AbstractJobDriverLocationServices abstractJobDriverLocationServices;
        private readonly AbstractJobRatingsServices abstractJobRatingsServices;
        private readonly AbstractJobBillOfLoadingServices abstractJobBillOfLoadingServices;
        #endregion

        #region Ctor

        public JobsFinderController(AbstractJobBidsServices jobBidsServices,
            AbstractJobServices jobServices,
            AbstractJobActivityServices jobActivityServices,
            AbstractJobDriverCommentsServices jobDriverCommentsServices,
            AbstractJobCommentsServices jobCommentsServices,
            AbstractJobDocumentsServices jobDocumentsServices,
            AbstractJobDriverLocationServices abstractJobDriverLocationServices,
            AbstractJobRatingsServices abstractJobRatingsServices,
            AbstractJobBillOfLoadingServices abstractJobBillOfLoadingServices)
        {
            this.jobBidsServices = jobBidsServices;
            this.jobActivityServices = jobActivityServices;           
            this.jobServices = jobServices;
            this.jobDriverCommentsServices = jobDriverCommentsServices;
            this.jobCommentsServices = jobCommentsServices;
            this.jobDocumentsServices = jobDocumentsServices;
            this.abstractJobDriverLocationServices = abstractJobDriverLocationServices;
            this.abstractJobRatingsServices = abstractJobRatingsServices;
            this.abstractJobBillOfLoadingServices = abstractJobBillOfLoadingServices;
        }
        #endregion

        #region Methods
        public ActionResult Index()
        {
            //PageParam pageParam = new PageParam();
            //var result = abstractJobDriverLocationServices.JobDriverLocation_ByJobId(pageParam, JobId, 0);
            //var result2 = jobServices.Job_ById(JobId);
            //if (result.Values.Count > 0)
            //{
            //    ViewBag.Latitude = result.Values[result.Values.Count-1].Latitude;
            //    ViewBag.Longitude = result.Values[result.Values.Count - 1].Longitude;
            //    ViewBag.CapturedDate = result.Values[result.Values.Count - 1].CapturedDate;
            //}
            //else
            //{
            //    ViewBag.Latitude = 0.0;
            //    ViewBag.Longitude = 0.0;
            //    ViewBag.CapturedDate = "";
            //}
            //ViewBag.JobId = JobId;
            //if (result2 != null && result2.Code == 200 && result2.Item != null)
            //{
            //    ViewBag.JobNo = result2.Item.JobNo;
            //}
            //else
            //{
            //    ViewBag.JobNo = "";
            //}
            return View();
        }


        public JsonResult TruckLocationCo(string JobNo, string lat, string lon, string dist)
        {
            List<JobDriverLocation> obj = new List<JobDriverLocation>();
            SqlConnection con = new SqlConnection(Configurations.ConnectionString);
            DataTable dt = new DataTable();
            string var_sql = "select Id from Job where JobNo='" + JobNo + "'";
            SqlDataAdapter sda = new SqlDataAdapter(var_sql,con);
            sda.Fill(dt);
            int JobId = 0;
            if(dt.Rows.Count > 0)
            {
                JobId = Convert.ToInt32(dt.Rows[0]["Id"]);
            }
            else
            {
                JobId = -1;
            }
            PageParam pageParam = new PageParam();
            var result = abstractJobDriverLocationServices.JobDriverLocation_ByJobId(pageParam, JobId, 0);
            for(int i=0; i < result.Values.Count; i++)
            {
                var sCoord = new GeoCoordinate(ConvertTo.Double(result.Values[i].Latitude), ConvertTo.Double(result.Values[i].Longitude));
                var eCoord = new GeoCoordinate(Convert.ToDouble(lat), Convert.ToDouble(lon));
                double distance = sCoord.GetDistanceTo(eCoord);
                if(distance <= (Convert.ToDouble(dist)*1000))
                {
                    JobDriverLocation locObj = new JobDriverLocation();
                    locObj.Latitude = result.Values[i].Latitude;
                    locObj.Longitude = result.Values[i].Longitude;
                    obj.Add(locObj);
                }
            }
            return Json(obj, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

CargoXpress/Views/Shared/_Header.cshtml
<!--  BEGIN NAVBAR  -->
<div class="header-container fixed-top">
    <header class="header navbar navbar-expand-sm expand-header">
        <a href="javascript:void(0);" class="sidebarCollapse" data-placement="bottom"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg></a>
        <ul class="navbar-item flex-row ml-auto">
            <li class="nav-item dropdown user-profile-dropdown  order-lg-0 order-1">
                <a href="javascript:void(0);" class="nav-link dropdown-toggle user" id="userProfileDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user-check"><path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="8.5" cy="7" r="4"></circle><polyline points="17 11 19 13 23 9"></polyline></svg>
                </a>
                <div class="dropdown-menu position-absolute e-animated e-fadeInUp" aria-labelledby="userProfileDropdown">
                    <div class="user-profile-section">
                        <div class="media mx-auto">
                            <img src="~/Images/90x90.jpg" class="img-fluid mr-2" alt="avatar">
                            <div class="media-body">
                                <h5>Alan Green</h5>
                                <p>Web Developer</p>
                            </div>
                        </div>
                    </div>
                    <div class="dropdown-item">
                        <a href="#">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-log-out"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg> <span>Log Out</span>
                        </a>
                    </div>
                </div>
            </li>
        </ul>
    </header>
</div>
<!--  END NAVBAR  -->

CargoXpress/Views/Shared/_Layout.cshtml
@using CargoXpress.Common;
@using CargoXpress.Pages;
@using System.Web.Optimization;
@using CargoXpress.Infrastructure;

@{
    /**/

    var curController = Convert.ToString(ViewContext.RouteData.Values["Controller"]);
    var curAction = Convert.ToString(ViewContext.RouteData.Values["Action"]);
}

<!DOCTYPE html>

<html>
<head>
    <title>Cleaning  | @ViewBag.Title  </title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

    <link rel="icon" href="~/favicon.ico" type="image/x-icon">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="~/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/vendor/font-awesome/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/assets/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.min.css">
    <link rel="stylesheet" href="~/assets/vendor/bootstrap-multiselect/bootstrap-multiselect.css">
    <link rel="stylesheet" href="~/assets/vendor/summernote/dist/summernote.css" />
    <link rel="stylesheet" href="~/assets/vendor/dropify/css/dropify.min.css">
    <link rel="stylesheet" href="~/assets/vendor/chartist/css/chartist.min.css">
    <link rel="stylesheet" href="~/assets/vendor/sweetalert/sweetalert.css" />
    <link rel="stylesheet" href="~/assets/vendor/sweetalert/sweetalert.css" />
    <link rel="stylesheet" href="~/Styles/datatables.min.css" />
    <link rel="stylesheet" href="~/Styles/datatables.bootstrap.css" />
    @*<link rel="stylesheet" href="~/assets/vendor/jquery-datatable/dataTables.bootstrap4.min.css">*@
    <link rel="stylesheet" href="~/assets/vendor/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css">
    <link rel="stylesheet" href="~/assets/vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.css">
    <link rel="stylesheet" href="~/assets/vendor/toastr/toastr.min.css">
    <link rel="stylesheet" href="~/assets/vendor/select2/select2.css" />

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="~/assets/vendor/css/main.css">
    <link rel="stylesheet" href="~/assets/vendor/css/color_skins.css">

    <style>
        .or_logo {
            width: 149px !important;
        }

        @@media only screen and (max-width: 992px) {

            .mobile_logo {
                width: 80px !important;
            }
        }
    </style>

    @*<link rel="stylesheet" href="~/assets/validation/css/components-md.min.css" />*@


    <script src="~/assets/validation/js/jquery.min.js"></script>
    <script src="~/assets/validation/js/bootstrap.min.js"></script>
    <script src="~/assets/validation/js/jquery.blockui.min.js"></script>
</head>
<body class="theme-orange">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            @*<div class="m-t-30"><img src="~/assets/images/logo-white.png" width="48" height="48" alt="Lucid"></div>*@
            <h3>Please wait...</h3>
        </div>
    </div>
    <!-- Overlay For Sidebars -->

    <div id="wrapper">
        <nav class="navbar navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-btn">
                    <button type="button" class="btn-toggle-offcanvas"><i class="lnr lnr-menu fa fa-bars"></i></button>
                </div>

                <div class="navbar-brand">
                    @*<a href="@Url.Action(Actions.Index,Controllers.Home,new { Area = ""})"><h5>AMC Database</h5></a>*@
                    <img src="" style="width: 77px !important;" alt="Cleaning  Logo" class="img-responsive logo or_logo mobile_logo">
                </div>

                <div class="navbar-right">

                    <div id="navbar-menu">
                        <ul class="nav navbar-nav">
                            <li><a title="Change Password" href="@Url.Action(Actions.ChangePassword,Controllers.AdminUser)" class="icon-menu"><i class="icon-settings"></i></a></li>
                            <li><a title="Log Out" href="@Url.Action(Actions.Logout,Controllers.Account)" class="icon-menu"><i class="icon-login"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

        <div id="left-sidebar" class="sidebar">
            <div class="sidebar-scroll">
                <div class="user-account">
                    <div class="dropdown">
                        <span>
                            Welcome, <strong>@ProjectSession.UserName</strong>
                        </span>
                        <a href="javascript:void(0);" class="user-name"><strong></strong></a>
                    </div>
                    <hr>
                </div>

                <!-- Left menu -->
                <div class="tab-content p-l-0 p-r-0">
                    <div class="tab-pane animated fadeIn active" id="hr_menu">
                        <nav class="sidebar-nav">
                            @Html.Partial("_LeftMenu")
                        </nav>
                    </div>
                </div>
            </div>
        </div>

        <div id="main-content">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>

    <!-- Javascript -->
    @RenderSection("dashboardscripts", required: false)
    <script src="~/assets/bundles/vendorscripts.bundle.js"></script>
    <script src="~/assets/bundles/mainscripts.bundle.js"></script>

    <script>
        $(document).ready(function () {
            setSelectedMenu();
        });

        function setSelectedMenu() {
            $(".main-menu").find("li.active").each(function () {
                $(this).removeClass("active");
            });
            switch ('@curController') {
                case '@Controllers.Dashboard':
                    setActiveLink($('#Dashboard').attr('id'));
                    break;
                 case '@Controllers.Customers':
                    setActiveLink($('#Customers').attr('id'));
                    break;
                 case '@Controllers.MasterPlans':
                    setActiveLink($('#MasterPlans').attr('id'));
                    break;
                    @*case '@Controllers.Jobs':
                    setActiveLink($('#Jobs').attr('id'));
                    break;
                case '@Controllers.MasterPricingPlans':
                    setActiveLink($('#PricingPlans').attr('id'));
                    break;
                 case '@Controllers.Support':
                    setActiveLink($('#Support').attr('id'));
                    break;
                case '@Controllers.QuickTracking':
                    setActiveLink($('#QuickTracking').attr('id'));
                    break;*@
                @*case '@Controllers.Master':
                    setActiveLink($('#Master').attr('id'));
                    setSubActiveLink('@curAction');
                    break;
                case '@Controllers.Users':
                    setActiveLink($('#Users').attr('id'));
                    break;*@
            }
        }

        function setActiveLink(menuId) {
            $(".custom").find("a[id='" + menuId + "']").parent("li").addClass("active");
            //$(".items").find("a[id='" + menuId + "']").parent("li").append("<span class='selected'></span>");
        };

        function setSubActiveLink(menuId) {
            $(".custom").find("a[id='" + menuId + "']").parent("li").addClass("active");
            //$(".items").find("a[id='" + menuId + "']").parent("li").append("<span class='selected'></span>");
        };
    </script>
    @RenderSection("scripts", required: false)
    @Html.Raw(ViewBag.openPopup)
</body>
</html>

CargoXpress/Views/Shared/_LeftMenu.cshtml
@using CargoXpress.Common;
@using CargoXpress.Pages;

  
<ul class="main-menu metismenu">
    <li class="custom"><a href="@Url.Action(Actions.Index,Controllers.Dashboard,new { Area=""})" id="Dashboard"><i class="icon-speedometer"></i><span>Dashboard</span></a></li>
    @*<li class="custom"><a href="@Url.Action(Actions.Index,Controllers.Shippers,new { Area=""})" id="Shippers"><i class="fa fa-address-card"></i>Shippers</a></li>
        <li class="custom"><a href="@Url.Action(Actions.Index,Controllers.Carriers,new { Area=""})" id="Carriers"><i class="fa fa-list-alt"></i>Carriers</a></li>
        <li class="custom"><a href="@Url.Action(Actions.Index,Controllers.Jobs,new { Area=""})" id="Jobs"><i class="fa fa-briefcase"></i>Jobs  </a></li>
        <li class="custom"><a href="@Url.Action(Actions.Index,Controllers.MasterPricingPlans,new { Area=""})" id="PricingPlans"><i class="fa fa-usd"></i>Manage Pricing Plans</a></li>
        <li class="custom"><a href="@Url.Action(Actions.Index,Controllers.Support,new { Area=""})" id="Support"><i class="fa fa-ticket"></i>Support Tickets</a></li>
        <li class="custom"><a href="@Url.Action(Actions.Index,"JobsFinder",new { Area=""})" id="QuickTracking"><i class="fa fa-location-arrow"></i>Quick Tracking</a></li>*@

    <li class="custom"><a href="@Url.Action(Actions.Index,Controllers.Customers,new { Area=""})" id="Customers"><i class="icon-users"></i>Customers</a></li>
    <li class="custom"><a href="@Url.Action(Actions.Index,Controllers.MasterPlans,new { Area=""})" id="MasterPlans"><i class="fa fa-briefcase"></i>Manage Plans  </a></li>
    <li class="custom"><a href="@Url.Action(Actions.Logout,Controllers.Account,new { Area=""})" id="Support"><i class="icon-logout"></i>Logout</a></li>

</ul>